services:
  - type: web
    name: churn-predictor-app
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && cd ../frontend && npm install && npm run build && cp -r build ../backend/
    startCommand: cd backend && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PORT
        value: 10000
    buildFilter:
      paths:
        - backend/
        - frontend/
    autoDeploy: true
